name: CI (Build)

on:
  push:

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-dotnet@v3

      - name: Install msgfmt
        run: sudo apt-get install -y gettext

      - name: Build TShockAPI.sln
        run: dotnet build TShockAPI.sln
