name: Deploy NuGet(OTAPI3)

on:
  push:
    branches: [ nuget-release ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.400
    - name: Install msgfmt
      run: sudo apt-get install -y gettext
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
          dotnet build ./TShockLauncher/ --configuration Release --no-restore
          dotnet build ./TShockPluginManager/ --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    # Publish to nuget
    - name: Push packages
      run: dotnet nuget push TShockAPI/bin/Release/*.nupkg TShockLauncher/bin/Release/*.nupkg TShockPluginManager/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
